name: '10,000 Faces'
favicon: null
layout_spectrum: 0.93878
typography_spectrum: 0.1509117274545133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3125
  lightness: 0.765067471191287
  saturation: 0.05749761615879834
  rhythmicContrast: 0.5
purpose: []
